# Generated by Django 2.1.dev20180514000620 on 2018-05-31 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
