# Generated by Django 2.0.5 on 2018-06-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boarding',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='temp',
        ),
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
